// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoQKNDcaEdMEKVlw9DVlY34pVLCIBHZ_E',
    appId: '1:1001980112726:web:928a02c74fc05bc5fa70f7',
    messagingSenderId: '1001980112726',
    projectId: 'dailyblogproject-e323c',
    authDomain: 'dailyblogproject-e323c.firebaseapp.com',
    storageBucket: 'dailyblogproject-e323c.appspot.com',
    measurementId: 'G-84CRHXGY2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8pzRb6x-eUTzqDj5vginELMQHu9WxX8M',
    appId: '1:1001980112726:android:a1e6109bf29e3245fa70f7',
    messagingSenderId: '1001980112726',
    projectId: 'dailyblogproject-e323c',
    storageBucket: 'dailyblogproject-e323c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACGeDiASzz8LpUj5NISmeBUIJ8Thoq0PY',
    appId: '1:1001980112726:ios:2cd5135b89e0fe9bfa70f7',
    messagingSenderId: '1001980112726',
    projectId: 'dailyblogproject-e323c',
    storageBucket: 'dailyblogproject-e323c.appspot.com',
    iosClientId: '1001980112726-rpm7mk99vnib6klplq6irbr58j38kbuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailystudioBlogProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACGeDiASzz8LpUj5NISmeBUIJ8Thoq0PY',
    appId: '1:1001980112726:ios:2cd5135b89e0fe9bfa70f7',
    messagingSenderId: '1001980112726',
    projectId: 'dailyblogproject-e323c',
    storageBucket: 'dailyblogproject-e323c.appspot.com',
    iosClientId: '1001980112726-rpm7mk99vnib6klplq6irbr58j38kbuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailystudioBlogProject',
  );
}
